### ISSUE TITLE
prose.sh: image URL with suffix still requires additional `ext:` options

### ISSUE THREAD

**Issue by imcotton** [picosh/pico#104]
i.e.

    /photo.jpg/ext:jpg

otherwise plain `/photo.jpg` only gives `webp` image.

_btw: the image I uploaded was `photo.jpg` (with suffix)._

**Comment by neurosnap** [comment]
Thanks for the bug report, this should be fixed now.  Could you please confirm on your end?

**Comment by imcotton** [comment]
Thanks for the quick fix, I can confirm it's working in above cases.

One small issue I noticed with extensionless on **Safari** and macOS **Catalina** (version **10.15**):

> request

```
:method: GET
:scheme: https
:authority: bower.sh
:path: /profile
Accept: image/png,image/svg+xml,image/*;q=0.8,video/*;q=0.8,*/*;q=0.5
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15
```

> response

```
:status: 200
Content-Type: image/webp
```

from MDN:

> [!NOTE]
> On Safari for macOS, WebP support depends on both Safari and macOS versions. You need Safari 14 or later as well as **macOS Big Sur (11) or a more recent version**. [^mdn]



[^mdn]: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types#sect7

**Comment by imcotton** [comment]
@neurosnap below is screen shot taken from **Safari** (15.6) on macOS **Catalina** (10.15) for example:

<img width="800" alt="Screen Shot 2024-03-24 at 6 46 22 PM" src="https://github.com/picosh/pico/assets/149541/7737265e-e1ba-4c72-b9ac-8410f9a22291">
