### ISSUE TITLE
pgs: need `xsl` file format support

### ISSUE THREAD

**Issue by jetjinser** [picosh/pico#105]
The static web page generated by [forester](https://sr.ht/~jonsterling/forester/) includes a `forest.xsl`.

**Comment by neurosnap** [comment]
Hi!  Thanks so much for submitting this issue.

I have deployed a fix, could you please try to upload `.xsl` again to confirm it works?

**Comment by jetjinser** [comment]
works fine!
It's awesome that you fixed it so quickly :)
