### ISSUE TITLE
Enable uploading webfinger files

### ISSUE THREAD

**Issue by weiji14** [picosh/pico#113]
Hi there,

Been trying out pgs.sh and it's been great so far! I'm wondering if it's possible to add [`webfinger`](https://indieweb.org/WebFinger) to the allow-list at https://pico.sh/pgs#what-file-types-are-supported? I'd like to upload a `.well-known/webfinger` file to enable some basic ActivityPub integration (see e.g. https://docs.joinmastodon.org/spec/webfinger/#example).

Thanks

**Comment by neurosnap** [comment]
Hi!  This was a bug in our file uploading validation logic.  I deployed a fix, could you please try it again and let me know if it's fixed?  Thanks!

**Comment by weiji14** [comment]
Perfect! Yes, uploading a `.well-known/webfinger` file works now :smile: Thanks for the quick fix!
