### ISSUE TITLE
Unable to scp specific files to prose.sh

### ISSUE THREAD

**Issue by zaf00130** [picosh/pico#131]
Attempting to upload _style.css and favicon.ico to prose.sh but files are being rejected due to filetype.

_style.css                                                                                                          100%  115     1.2KB/s   00:00
WARNING: (_style.css) invalid file, format must be (.md,.jpg,.jpeg,.png,.gif,.webp,.svg), skipping

scp favicon.ico prose.sh:/
favicon.ico                                                                                                         100% 9610    88.7KB/s   00:00
ERROR: (favicon.ico) invalid file, format must be (.md,.jpg,.jpeg,.png,.gif,.webp,.svg), skipping

I also tried uploading them as an acceptable filetype and then changing the extension but was also denied that action as well

**Comment by neurosnap** [comment]
File should be "_styles.css"

I'll look into the ico

**Comment by neurosnap** [comment]
I deployed a fix to allow `.ico` file formats to be uploaded to prose.sh -- could you please confirm your issues are fixed?
