### ISSUE TITLE
I have replaced my computer, and I know the public key. But how can I connect to my blog?

### ISSUE THREAD

**Issue by jaychoubaby** [picosh/pico#24]
Hope to get some help

**Comment by neurosnap** [comment]
Hi! Do you have access to your private key?

**Comment by jaychoubaby** [comment]
The thing is, I created my space while using Pico, but my computer broke down and I reinstalled the system, so I couldn't connect to my space anymore

**Comment by neurosnap** [comment]
Can you email me your username, original public key, and new public key?

**Comment by jaychoubaby** [comment]
> I have already sent you an email, please check it.
