### ISSUE TITLE
Unlisted posts (lists.sh)

### ISSUE THREAD

**Issue by ayoayco** [picosh/pico#29]
Just an idea for a feature to mark a post as "unlisted" -- that is, not seen on users' profiles and also opted-out of the "discover" feed, but can be seen by anyone with the URL.

**Comment by neurosnap** [comment]
Adding “draft: true” or setting the date to the future will do what you want.

**Comment by ayoayco** [comment]
@neurosnap thanks for responding! Do you meen metadata on the text file like this `=: draft true`?

I tried on [this list](https://ayo.lists.sh/bluray-collection) to test but it's still showing up on [my profile](https://ayo.lists.sh)

**Comment by neurosnap** [comment]
Ohh you’re using lists.sh

pushing the date forward in the future will do what you want in that case.

I should add draft to lists as well, good idea!

**Comment by ayoayco** [comment]
Oh yeah, should have mentioned lists.sh :) Thanks will use the date for now!

**Comment by neurosnap** [comment]
Sorry for the late reply!  We will happily accept PRs!  If you have questions about how to setup the project locally, feel free to join our IRC channel #pico.sh @ libera.chat

**Comment by neurosnap** [comment]
Closing because we are shutting lists.sh down.  Thanks for your interest!

**Comment by geek-9** [comment]
finger is natural way to read wish list etc.

**Comment by ayoayco** [comment]
@neurosnap you have interesting projects! Thanks for working on them :)
