### ISSUE TITLE
Cannot upload files anymore: `WARNING: (/) invalid file, format must be (.md), skipping`

### ISSUE THREAD

**Issue by chrisgrieser** [picosh/pico#36]
Hi, thanks a lot for prose.sh, been using it for a while as a simple and minimal publishing solution!

So today, I wanted to publish a new post like I did a bunch of times before, and now I get this error message: 
```bash
> scp "$HOME/foobar.md" prose.sh:                                              100% 2126    19.4KB/s   00:00
WARNING: (/) invalid file, format must be (.md), skipping
```

What confuses me is that it is complaining about the file format, which is literally the correct one? The prose help page does not mention anything like this, and previously this sort of `scp` command worked without any issues.

**Comment by neurosnap** [comment]
Probably a regression from our work on `pgs.sh`, I'll take a look asap

**Comment by neurosnap** [comment]
Current workaround: `scp foobar.md prose.sh:/foodbar.md`
