### ISSUE TITLE
Could you add replay ID the same as fido/twitter/groups/gitcommit for posts

### ISSUE THREAD

**Issue by irramail** [picosh/pico#4]
Or something similar, and show/screen it on http/rss/email

And approved@/rejected@ id or usersubdomain

Can I help you anything?

**Comment by neurosnap** [comment]
Greetings!  I don't quite understand what you are asking for, could you please explain more what you are requesting?  Thanks!

**Comment by irramail** [comment]
Hello, I want to have comments for my posts on prose.sh, by ssh from another users.
User should send ssh key to my prose.sh account and I can approve or reject this request.
If I approved request with ssh-key, user can use scp for my post in directory post123/comments.
