### ISSUE TITLE
"you do not have access to this service" for all pgs.sh operation

### ISSUE THREAD

**Issue by thornewolf** [picosh/pico#41]
Created a directory structure 
`ls -R`
```
directory  index.html

./directory:
a.txt
```

then attempted 
`scp -r * pgs.sh:/demo`
and
`scp -r * pgs.sh:/asndnas`

Error
```
you do not have access to this service
scp: Connection closed
```

then attempted
`ssh pgs.sh help`

same error

**Comment by neurosnap** [comment]
Hi!

https://pgs.sh is currently in closed-beta. If you would like to receive an invite to our service, please join our IRC channel #pico.sh @ libera.chat

Thanks!

**Comment by neurosnap** [comment]
pgs is now generally available, closing
