### ISSUE TITLE
"not found" when linking to prose.sh post with / at the end

### ISSUE THREAD

**Issue by johanvandegriff** [picosh/pico#64]
Not sure if this is intended or not, but when I imported stuff from hugo I realized I had sometimes linked between pages with an extra / at the end, but that doesn't work on prose.sh. For example:

this link works: https://johanv.prose.sh/best

this link doesn't work: https://johanv.prose.sh/best/

**Comment by neurosnap** [comment]
Most likely a bug in our end. Will take a look later this week.
