### ISSUE TITLE
imgs.sh fails for filenames with more than one "."

### ISSUE THREAD

**Issue by johanvandegriff** [picosh/pico#65]
When I upload an image file to imgs.sh with more than one ".", for example "wahoo.1.jpeg", it says it worked, but viewing it in the browser gives a "not found" error.

```bash
scp wahoo.1.jpeg imgs.sh:
https://johanv.imgs.sh/wahoo.1 (space: 0.03/1.00GB, 2.60%)
```

but when I go to https://johanv.imgs.sh/wahoo.1 I get "image not found johanv/wahoo"

works for the same file with just one ".":
```bash
scp wahoo.jpeg imgs.sh:
https://johanv.imgs.sh/wahoo (space: 0.03/1.00GB, 2.60%)
```
and this link works: https://johanv.imgs.sh/wahoo
additionally, the old link now works but it finds the new image instead

**Comment by neurosnap** [comment]
Thanks for the bug report! Probably a bug on our end, will investigate later this week.
