### ISSUE TITLE
[prose.sh] _styles.css detected as invalid file

### ISSUE THREAD

**Issue by ivanhercaz** [picosh/pico#74]
Hi!
I was trying to update my current `_styles.css` as I already did in the past, but not the `scp` command returns me the error:

```
ERROR: (_styles.css) invalid file, format must be (.md,.jpg,.jpeg,.png,.gif,.webp,.svg), skipping
```

I checked the [prose.sh documentation](https://pico.sh/prose#how-can-i-change-the-theme-of-my-blog) to check if anything changes (maybe another name for the file, but not).

Thanks in advance for your attention and your work!

**Comment by neurosnap** [comment]
Hi!  Thanks so much for reaching out.  Fix has been deployed, could you please try again?

**Comment by ivanhercaz** [comment]
Thank you for your fast answer and fix! Now it works as before.
