### ISSUE TITLE
[pgs.sh] Custom headers

### ISSUE THREAD

**Issue by AverageHelper** [picosh/pico#82]
I see pgs.sh supports a special `_redirects` file to configure custom redirect paths. That's super neat!

Could a special `_headers` file be used to configure custom response headers, similar to [what Netlify offers](https://docs.netlify.com/routing/headers/)?

**Comment by neurosnap** [comment]
Hi, thanks for posting!

Yes we should probably support a `_headers` file.  I'm wondering if we should deprecate `_redirects` and just go all in on a single configuration file, thoughts?

**Comment by AverageHelper** [comment]
I don't much care either way. Personally I'd prefer a `_headers` file, since that's what I'm used to from Netlify and Cloudflare Pages, but I'm not opposed to learning a new system for the same behavior if need be.

**Comment by neurosnap** [comment]
Got it.  We will commit to implementing a `_headers` file for now.  I'll update this ticket with progress.

**Comment by neurosnap** [comment]
This feature has been deployed.  Please try it out and let me know if it does or does not work properly.  Thanks again!

**Comment by AverageHelper** [comment]
It seems to work! Thank you very much!
