### ISSUE TITLE
Mistakenly generated new ssh-key can't get my old account now

### ISSUE THREAD

**Issue by RayyanNafees** [picosh/pico#86]
My older account was rayyan@pico.sh

I mistakenly ran the ssh-keygen command and overwritten my existing ssh rsa key on y system

now i can't log back into that and had to create a new account named nafees@pico.sh

Any way I can get my account back ?

I really needed the domains of rayyan.pico.sh & rayyan.prose.sh & rayyan.pastes.sh

**Comment by neurosnap** [comment]
Hi!  I've sent you an email so we can help you out.  Closing and continuing our convo via email
