### ISSUE TITLE
Prose.sh: I think there should be a 'link' meta tag to aid auto-discovery of the RSS feed.

### ISSUE THREAD

**Issue by allanderek** [picosh/pico#9]
So if you attempt to add a feed to a feedreader by just entering the url of the blog this doesn't work, you have to enter the actual URL of the feed, making this a little inconvenient for readers.

I'm not sure how you do this, but I believe you need to add a link tag such as:

```
<link rel="alternate" type="application/rss+xml" title="RSS" href="/rss/" />
```

or maybe it's 'atom+xml' instead of 'rss+xml':

```
<link rel="alternate" type="application/atom+xml" title="RSS" href="/rss/" />
```

**Comment by neurosnap** [comment]
Oh interesting! We will happily accept any PRs for this feature!
