### ISSUE TITLE
gopher or finger

### ISSUE THREAD

**Issue by geek-9** [picosh/pico#98]
Is possible add gopher protocol https://simple.wikipedia.org/wiki/Gopher_(protocol) or finger or gemini https://en.wikipedia.org/wiki/Gemini_(protocol) ?
HTML is ok but gopher are smallest

**Comment by neurosnap** [comment]
Hi!  We originally had support for gemini but eventually removed it because it was non-trivial to maintain and there we very little usage.  I'd be happy to re-evaluate if there is a lot of traction for this idea, but there are technical limitations that are too great for their usage atm.

**Comment by neurosnap** [comment]
We are not going to implement this feature so closing for now.  Thanks for your feedback!
