### ISSUE TITLE
Interactions with other users

### ISSUE THREAD

**Issue by geek-9** [picosh/pico#99]
When I post my blog post I need add some interactions.
Meybe add hearth, hand, +, - etc interaction 
or(and) similar slashdot or lobste.rs voting to the post on summarise web page with all posts.

I no need comments. I can put my email or mastodon account on web page if I can get feedback. But small (turn on/off) up/down voting will be nice

**Comment by neurosnap** [comment]
Hi!  We are going to experiment with a link aggregator service using much of the same tech.  That's where I think voting would make more sense.  We are trying to keep prose as simple and decluttered as possible

**Comment by geek-9** [comment]
I found way to hide my blog post ;) in summarise list 

this post not appear https://pro.prose.sh/index.html
(look date, and look 'unlisted' near title)

**Comment by neurosnap** [comment]
Thanks for your feedback, we don't have any feature plans to allow users to interact with each other within our platform.  Closing for now.
